version: "3.9"
services:
  # sudo chown -R 472:472 ${USER_DIR}/grafana
  grafana:
    image: grafana/grafana:10.3.4@sha256:a4c1fa9b108073012f06178259c534a27d7d3b51fbf40eac263f0e74ee403c0b
    container_name: grafana
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ${USER_DIR}/grafana:/var/lib/grafana
    expose:
      - 3000
      # healthcheck:
      #   test: ["CMD-SHELL", "wget --quiet --tries=1 --spider https://grafana.${DOMAIN_NAME}/api/health || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)
      - traefik.http.routers.grafana.middlewares=chain-authelia@file
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
